Fix tarantoolctl options
tarantoolctl included in Tarantool 1.10 requires to pass a server with
=. Otherwise it produces an error:

Error: Invalid argument: flag --server=<server> expects a parameter. See --help.
Error: Process completed with exit code 1.

1. https://github.com/tarantool/ddl/runs/4143555113?check_suite_focus=true